; Unreal — preset NVCleanInstall Gaming / Unreal (suggestion, non officiel)
; Composants : 1 = installer, 0 = ne pas installer
DisplayDriver=1
PhysX=0
NVIDIA_DLSS=0
LegacyControlPanel=0
HDAudio=0
VCpp2017=0
USBC=0
FrameViewSDK=0
QuadroView=0
VirtualAudio=0
Telemetry=0
NVPlatformControllers=0
NVIDIAApp=0
NVContainer=0
ShadowPlay=0
NVBackend=0
NVIDIAAppMessageBus=0
; Tweaks
DisableInstallerTelemetry=1
UnattendedExpressInstallation=0
PerformCleanInstallation=1
AddHardwareSupport=0
EnableDLSSIndicator=0
DisableMPO=1
DisableAnsel=1
ShowExpertTweaks=1
DisableDriverTelemetry=1
DisableNVIDIAContainer=0
DisableHDAudioSleepTimer=0
EnableMSI=1
InterruptPolicy=Default
InterruptPriority=Default
DisableHDCP=1
ApplyNVENCPatch=0
StartExternalApp=0
RebuildDigitalSignature=1
EACCompatibleMethod=1
AutoAcceptUnsignedWarning=1